# Generated by Django 2.2 on 2019-04-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wechat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='微信'),
        ),
    ]
