# Generated by Django 2.2 on 2019-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_user_wechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/avatar/default.png', max_length=200, null=True, upload_to='uploads/avatar/%Y/%m', verbose_name='用户头像'),
        ),
    ]
