# Generated by Django 2.2 on 2019-04-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20190404_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='菜鸟', max_length=20, verbose_name='等级名称')),
                ('start', models.IntegerField(default=0, verbose_name='积分下限')),
                ('end', models.IntegerField(default=0, verbose_name='积分上限')),
            ],
            options={
                'verbose_name': '积分',
                'verbose_name_plural': '积分',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disabled', models.BooleanField(default=False, verbose_name='删除')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('FromIP', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('FromPlatform', models.CharField(max_length=300, null=True, verbose_name='平台')),
                ('ModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('name', models.CharField(default='普通', max_length=20, verbose_name='等级名称')),
                ('code', models.IntegerField(default=0, verbose_name='编号')),
                ('privilege', models.CharField(blank=True, max_length=300, null=True, verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['-code'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='accumulate',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
    ]
