# Generated by Django 2.2 on 2019-04-03 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disabled', models.BooleanField(default=False, verbose_name='删除')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('FromIP', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('FromPlatform', models.CharField(max_length=300, null=True, verbose_name='平台')),
                ('ModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('Level', models.CharField(choices=[('一级', (('14', '计算机基础及WPS Office应用'), ('15', '计算机基础及MS Office应用'), ('16', '计算机基础及Photoshop应用'), ('17', '网络安全素质教育'))), ('二级', (('24', 'C语言程序设计'), ('26', 'VB语言程序设计'), ('28', 'Java语言程序设计'), ('29', 'Access数据库程序设计'), ('61', 'C++语言程序设计'), ('63', 'MySQL数据库程序设计'), ('64', 'Web程序设计'), ('65', 'MS Office高级应用'), ('66', 'Python语言程序设计'))), ('三级', (('35', '网络技术'), ('36', '数据库技术'), ('38', '信息安全技术'), ('39', '嵌入式系统开发技术'))), ('四级', (('41', '网络工程师'), ('42', '数据库工程师'), ('44', '信息安全工程师'), ('45', '嵌入式系统开发工程师')))], max_length=2, verbose_name='考试分类')),
                ('Desc', models.TextField(default='', verbose_name='题目')),
                ('Answer', models.TextField(default='', verbose_name='答案解析')),
                ('Difficulty', models.IntegerField(default=5, verbose_name='难度')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disabled', models.BooleanField(default=False, verbose_name='删除')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('FromIP', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('FromPlatform', models.CharField(max_length=300, null=True, verbose_name='平台')),
                ('ModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('Name', models.CharField(max_length=30, verbose_name='题目标签')),
            ],
            options={
                'verbose_name': '题目标签',
                'verbose_name_plural': '题目标签',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disabled', models.BooleanField(default=False, verbose_name='删除')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('FromIP', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('FromPlatform', models.CharField(max_length=300, null=True, verbose_name='平台')),
                ('ModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('Name', models.CharField(max_length=30, verbose_name='题目类型')),
                ('Desc', models.CharField(max_length=30, verbose_name='类型说明')),
            ],
            options={
                'verbose_name': '考题类型',
                'verbose_name_plural': '考题类型',
            },
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disabled', models.BooleanField(default=False, verbose_name='删除')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('FromIP', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('FromPlatform', models.CharField(max_length=300, null=True, verbose_name='平台')),
                ('ModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('Level', models.CharField(choices=[('一级', (('14', '计算机基础及WPS Office应用'), ('15', '计算机基础及MS Office应用'), ('16', '计算机基础及Photoshop应用'), ('17', '网络安全素质教育'))), ('二级', (('24', 'C语言程序设计'), ('26', 'VB语言程序设计'), ('28', 'Java语言程序设计'), ('29', 'Access数据库程序设计'), ('61', 'C++语言程序设计'), ('63', 'MySQL数据库程序设计'), ('64', 'Web程序设计'), ('65', 'MS Office高级应用'), ('66', 'Python语言程序设计'))), ('三级', (('35', '网络技术'), ('36', '数据库技术'), ('38', '信息安全技术'), ('39', '嵌入式系统开发技术'))), ('四级', (('41', '网络工程师'), ('42', '数据库工程师'), ('44', '信息安全工程师'), ('45', '嵌入式系统开发工程师')))], max_length=2, verbose_name='所属考试')),
                ('Name', models.CharField(max_length=30, verbose_name='题目主类型')),
                ('Desc', models.CharField(max_length=30, verbose_name='类型说明')),
                ('MainType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NCER.Type', verbose_name='类型')),
            ],
            options={
                'verbose_name': '题目子类型',
                'verbose_name_plural': '题目子类型',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disabled', models.BooleanField(default=False, verbose_name='删除')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('FromIP', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('FromPlatform', models.CharField(max_length=300, null=True, verbose_name='平台')),
                ('ModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('Option', models.TextField(default='', verbose_name='选项')),
                ('IsAnswer', models.BooleanField(verbose_name='是否为正确选项')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NCER.ChoiceQuestions', verbose_name='题目')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
        migrations.AddField(
            model_name='choicequestions',
            name='Tags',
            field=models.ManyToManyField(to='NCER.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='choicequestions',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='NCER.SubType', verbose_name='类型'),
        ),
    ]
