# Generated by Django 2.1.7 on 2019-03-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NCER', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='levels',
            options={'verbose_name': '考试等级', 'verbose_name_plural': '考试等级'},
        ),
        migrations.AddField(
            model_name='levels',
            name='Code',
            field=models.IntegerField(default=0, verbose_name='科目代码'),
        ),
    ]
