# Generated by Django 2.1.7 on 2019-03-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NCER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desc', models.TextField(default='', verbose_name='题目')),
                ('Answer', models.TextField(default='', verbose_name='答案解析')),
                ('Difficulty', models.IntegerField(default=5, verbose_name='难度')),
                ('Disabled', models.BooleanField(default=False, verbose_name='删除')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('ModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Option', models.TextField(default='', verbose_name='选项')),
                ('IsAnswer', models.BooleanField(verbose_name='是否为选项')),
                ('Disabled', models.BooleanField(default=False, verbose_name='删除')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('ModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
        migrations.CreateModel(
            name='CodeQuestions',
            fields=[
                ('choicequestions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Python.ChoiceQuestions')),
            ],
            options={
                'verbose_name': '编程题',
                'verbose_name_plural': '编程题',
            },
            bases=('Python.choicequestions',),
        ),
        migrations.AddField(
            model_name='options',
            name='Question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Python.ChoiceQuestions', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='choicequestions',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NCER.Levels', verbose_name='考试分类'),
        ),
        migrations.AddField(
            model_name='choicequestions',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NCER.SubType', verbose_name='类型'),
        ),
    ]
