# Generated by Django 2.1.7 on 2019-03-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Python', '0002_auto_20190328_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicequestions',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Level', to='NCER.Levels', verbose_name='考试分类'),
        ),
        migrations.AlterField(
            model_name='choicequestions',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='NCER.SubType', verbose_name='类型'),
        ),
    ]
