# Generated by Django 2.2 on 2019-04-03 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NCER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disabled', models.BooleanField(default=False, verbose_name='删除')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('FromIP', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('FromPlatform', models.CharField(max_length=300, null=True, verbose_name='平台')),
                ('ModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('Comment', models.TextField(verbose_name='评论内容')),
                ('Username', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户名')),
                ('Email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱地址')),
                ('ThumbUps', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('ParentID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Comment.Comments', verbose_name='父级评论')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NCER.ChoiceQuestions', verbose_name='题目')),
            ],
            options={
                'verbose_name': '留言评论',
                'verbose_name_plural': '留言评论',
            },
        ),
    ]
