# Generated by Django 2.1.7 on 2019-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disabled', models.BooleanField(default=False, verbose_name='删除')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('ModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('Desc', models.CharField(max_length=30, verbose_name='内容')),
            ],
            options={
                'verbose_name': '留言评论',
                'verbose_name_plural': '留言评论',
            },
        ),
    ]
