# Generated by Django 2.1.7 on 2019-04-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NCER', '0001_initial'),
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disabled', models.BooleanField(default=False, verbose_name='删除')),
                ('CreateTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('CreateBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='创建人')),
                ('ModifyTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('ModifyBy', models.CharField(blank=True, max_length=50, null=True, verbose_name='修改人')),
                ('Remark', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备注')),
                ('Comment', models.CharField(max_length=30, verbose_name='内容')),
                ('ParentID', models.CharField(default='root', max_length=64, verbose_name='父级评论')),
                ('ThumbUps', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NCER.ChoiceQuestions')),
            ],
            options={
                'verbose_name': '留言评论',
                'verbose_name_plural': '留言评论',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
